my_string = input("Введите текст: ")
print('В вашем тексте', len(my_string), 'символов.')
print('Текст в верхнем регистре:', my_string.upper())
print('Текст в нижнем регистре:', my_string.lower())
print('Текст без пробелов:', my_string.replace(' ',''))
print('Первый символ текста:', my_string[0])
print('Последний символ текста:', my_string[-1])
